In [1]:
from sklearn import datasets

In [2]:
iris= datasets.load_iris()
type(iris)

sklearn.utils.Bunch

* Bunch는 Dictionary를 따온 것임

In [3]:
iris

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [4]:
x = iris.data
y = iris.target
x.shape, y.shape, type(x), type(y)

((150, 4), (150,), numpy.ndarray, numpy.ndarray)

* 타입명이 numpy이기 때문에 numpy 명령어만을 사용할 수 있다 / Pandas 명령어 등은 사용 불가함에 유의!

In [5]:
import numpy as np

In [6]:
np.unique(y)

array([0, 1, 2])

* x는 독립변수, y는 종속변수

In [7]:
from sklearn.model_selection import train_test_split

In [8]:
x, y

(array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
        [5

In [9]:
x_train, x_test, y_train,y_test = train_test_split(x, y)
x_train.shape, x_test.shape, y_train.shape, y_test.shape

((112, 4), (38, 4), (112,), (38,))

In [10]:
from sklearn.linear_model import LogisticRegression

In [11]:
logR = LogisticRegression()

In [12]:
logR.fit(x_train, y_train)

LogisticRegression()

In [13]:
logR.coef_, logR.intercept_

(array([[-0.41879306,  0.84653259, -2.28751509, -0.99670818],
        [ 0.40111572, -0.47382352, -0.07947126, -0.80021273],
        [ 0.01767734, -0.37270907,  2.36698635,  1.79692091]]),
 array([  9.17076971,   2.562715  , -11.73348471]))

* y = -0.40760465x1 + 0.92201009x2 -2.3062051x3 -0.99740765x4 + 8.98178884
... 이렇게 3개의 직선식이 생성

In [14]:
logR.predict_proba(x_train[100:104])

array([[1.07840400e-02, 8.95849425e-01, 9.33665348e-02],
       [2.82900488e-05, 6.37395405e-02, 9.36232169e-01],
       [7.85787170e-05, 1.15426581e-01, 8.84494840e-01],
       [1.25358321e-01, 8.70342166e-01, 4.29951324e-03]])

In [15]:
logR.predict(x_train[100:104])

array([1, 2, 2, 1])

In [21]:
from sklearn import metrics

In [24]:
y_pred = logR.predict(x_train)
y_pred.shape, y_train.shape

((112,), (112,))

In [25]:
y_pred

array([2, 0, 0, 0, 0, 1, 0, 1, 2, 1, 0, 2, 0, 2, 2, 1, 1, 0, 2, 0, 1, 1,
       0, 0, 0, 1, 1, 0, 2, 2, 0, 0, 1, 1, 0, 1, 2, 1, 2, 0, 2, 2, 2, 1,
       0, 2, 0, 1, 2, 1, 0, 0, 0, 2, 2, 0, 0, 0, 0, 1, 0, 2, 1, 1, 0, 0,
       2, 2, 2, 1, 2, 0, 2, 1, 2, 1, 1, 1, 1, 2, 0, 0, 2, 1, 1, 0, 0, 2,
       2, 1, 0, 0, 1, 0, 0, 2, 2, 2, 1, 1, 1, 2, 2, 1, 2, 0, 2, 2, 2, 1,
       0, 0])

In [26]:
y_train

array([2, 0, 0, 0, 0, 1, 0, 1, 2, 1, 0, 2, 0, 2, 2, 1, 1, 0, 1, 0, 1, 1,
       0, 0, 0, 1, 1, 0, 2, 2, 0, 0, 1, 1, 0, 1, 2, 1, 2, 0, 2, 2, 2, 1,
       0, 2, 0, 1, 2, 1, 0, 0, 0, 2, 1, 0, 0, 0, 0, 1, 0, 2, 2, 1, 0, 0,
       2, 2, 2, 1, 2, 0, 2, 1, 2, 1, 1, 1, 1, 1, 0, 0, 2, 1, 1, 0, 0, 2,
       2, 1, 0, 0, 1, 0, 0, 2, 2, 2, 1, 1, 1, 2, 2, 1, 2, 0, 2, 2, 2, 1,
       0, 0])

In [27]:
metrics.classification_report(y_train, y_pred)

'              precision    recall  f1-score   support\n\n           0       1.00      1.00      1.00        41\n           1       0.97      0.92      0.94        36\n           2       0.92      0.97      0.94        35\n\n    accuracy                           0.96       112\n   macro avg       0.96      0.96      0.96       112\nweighted avg       0.97      0.96      0.96       112\n'

In [28]:
print(metrics.classification_report(y_train, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        41
           1       0.97      0.92      0.94        36
           2       0.92      0.97      0.94        35

    accuracy                           0.96       112
   macro avg       0.96      0.96      0.96       112
weighted avg       0.97      0.96      0.96       112

