<a href="https://colab.research.google.com/github/creamcheesesteak/test_machinelearning/blob/master/Kfold.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

class sklearn.model_selection.KFold(n_splits=5, *, shuffle=False, random_state=None)

In [1]:
import numpy as np

In [8]:
X = np.array([[1, 2], [3, 4], [1, 2], [3, 4],[5,6],[7,8],[9,10]])
y = np.array([1, 2, 3, 4, 2, 3, 1])

In [9]:
X.shape, y.shape
# X는 feature, Y는 label

((7, 2), (7,))

In [13]:
from sklearn.model_selection import KFold

In [18]:
kf = KFold(n_splits=2, shuffle=True)
kf.get_n_splits(X)

2

In [26]:
for first, second in kf.split(X):
  print(first, ':' ,second)
  x_train = X[first]
  print(x_train)
  x_test = X[second]
  print(x_test)
  lgbm.fit(x_train, y_train)
  score = lgbm.score(x_train, y_train)

[1 5 6] : [0 2 3 4]
[[ 3  4]
 [ 7  8]
 [ 9 10]]
[[1 2]
 [1 2]
 [3 4]
 [5 6]]


NameError: ignored

In [23]:
type(first), type(second), first.shape, second.shape

(numpy.ndarray, numpy.ndarray, (4,), (3,))